[build]
  command = "npm run build"
  publish = "dist"

[env]
  VITE_API_URL = "http://18.231.220.109"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "vite"
  targetPort = 5173
  port = 8888
  framework = "vite"